'use strict';
(function(){
const SB='https://guwdswqaqnhzqapflvey.supabase.co',KEY='sb_publishable_AfTScx4Qcwmk3dk8pCo9Fg_kZgglof9';
const TOKEN=localStorage.getItem('choco_access_token')||'',UID=localStorage.getItem('choco_user_id')||'',ROLE=localStorage.getItem('choco_role')||'';if(!TOKEN||!UID||ROLE!=='admin')return;
const $=id=>document.getElementById(id),dbg=t=>{if($('adminPushDebug'))$('adminPushDebug').innerHTML=t},b64=s=>{const p='='.repeat((4-s.length%4)%4),r=atob((s+p).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from(r,c=>c.charCodeAt(0))};
async function vapid(){const r=await fetch(SB+'/functions/v1/admin-send-push?mode=public',{headers:{apikey:KEY,Accept:'application/json'}}),t=await r.text();let j={};try{j=JSON.parse(t)}catch{}if(!r.ok||!j.vapid_public_key)throw Error('Không lấy được VAPID Public Key Admin');return b64(j.vapid_public_key.trim())}
async function enable(){const b=$('adminPush');if(b)b.disabled=true;try{if(!('serviceWorker'in navigator)||!('PushManager'in window))throw Error('Thiết bị không hỗ trợ Web Push');if(location.protocol!=='https:')throw Error('Web Push cần HTTPS');if(/iphone|ipad|ipod/i.test(navigator.userAgent)&&!(navigator.standalone===true||matchMedia('(display-mode:standalone)').matches))throw Error('iPhone cần mở Admin từ Màn hình chính (PWA)');const key=await vapid();if(key.length!==65||key[0]!==4)throw Error('VAPID Public Key không hợp lệ');const reg=await navigator.serviceWorker.register('./admin-push-sw.js?v=1',{scope:'./'});await navigator.serviceWorker.ready;let p=Notification.permission;if(p!=='granted')p=await Notification.requestPermission();if(p!=='granted')throw Error('Bạn chưa cho phép thông báo');let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:key});const j=sub.toJSON();if(!j.endpoint||!j.keys?.p256dh||!j.keys?.auth)throw Error('Subscription Admin thiếu dữ liệu');const r=await fetch(SB+'/rest/v1/rpc/upsert_admin_push_subscription',{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+TOKEN,'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({p_user_id:UID,p_endpoint:j.endpoint,p_p256dh:j.keys.p256dh,p_auth:j.keys.auth})});const t=await r.text();if(!r.ok)throw Error('Supabase Admin REST '+r.status+': '+t);localStorage.setItem('choco_admin_push_enabled','1');$('adminPushStatus').innerHTML='✅ <b>WEB PUSH ADMIN RIÊNG ĐÃ BẬT</b>';dbg('Admin Web Push: ACTIVE<br>Subscription: '+j.endpoint.slice(-45));if($('adminPushTest'))$('adminPushTest').disabled=false}catch(e){$('adminPushStatus').innerHTML='❌ <b>KHÔNG BẬT ĐƯỢC</b><br>'+e.message;dbg('❌ '+e.message);if(b)b.disabled=false}}
async function test(){const b=$('adminPushTest');if(b)b.disabled=true;dbg('⏳ Đang gửi TEST Admin...');try{const r=await fetch(SB+'/functions/v1/admin-send-push?mode=test',{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+TOKEN,Accept:'application/json'}}),t=await r.text();let j={};try{j=JSON.parse(t)}catch{}if(!r.ok||!j.ok)throw Error(j.error||t||('HTTP '+r.status));dbg('✅ ADMIN NATIVE ĐÃ GỬI<br>Target: '+j.target_count+'<br>Kiểm tra thông báo trên iPhone.')}catch(e){dbg('❌ TEST ADMIN: '+e.message)}finally{if(b)b.disabled=false}}
async function status(){if(localStorage.getItem('choco_admin_push_enabled')!=='1')return;try{const r=await fetch(SB+'/functions/v1/admin-send-push?mode=status',{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+TOKEN,Accept:'application/json'}}),t=await r.text();let j={};try{j=JSON.parse(t)}catch{}if(r.ok&&j.ok&&j.processed>0){dbg('🔔 Đã gửi '+j.processed+' thông báo trạng thái đơn cho Admin.')}}catch(e){console.warn('Admin status push',e)}}
function init(){const b=$('adminPush');const t=$('adminPushTest');if(b)b.onclick=enable;if(t)t.onclick=test;if(localStorage.getItem('choco_admin_push_enabled')==='1'){if($('adminPushStatus'))$('adminPushStatus').innerHTML='✅ <b>WEB PUSH ADMIN ĐÃ BẬT</b>';if(t)t.disabled=false}status();setInterval(status,10000)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
