/* CHOCO SHIP - ADMIN REVIEWS v1 */
'use strict';
(function(){
  if(window.__CHOCO_ADMIN_REVIEWS__)return;
  window.__CHOCO_ADMIN_REVIEWS__=true;
  const SB='https://guwdswqaqnhzqapflvey.supabase.co';
  const KEY='sb_publishable_AfTScx4Qcwmk3dk8pCo9Fg_kZgglof9';
  const esc=x=>String(x??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  function api(path,opt={}){const t=String(localStorage.getItem('choco_access_token')||'').trim();return fetch(SB+path,{...opt,headers:{apikey:KEY,Authorization:'Bearer '+t,Accept:'application/json','Content-Type':'application/json',...(opt.headers||{})}}).then(async r=>{if(!r.ok)throw Error(await r.text());return r.json()})}
  function inject(){if(document.getElementById('adminReviewsBox'))return;const s=document.createElement('style');s.textContent='#adminReviewsBox{background:#fff;border-radius:15px;padding:16px;margin-bottom:15px;box-shadow:0 2px 8px #ddd;border:1px solid #fed7aa}.ar-title{font-size:20px;font-weight:900;color:#c2410c}.ar-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:12px 0}.ar-stat{background:#fff7ed;border-radius:10px;padding:10px;text-align:center}.ar-stat b{display:block;font-size:21px}.ar-filter{display:flex;gap:7px;margin-bottom:10px}.ar-filter select{flex:1;padding:9px;border:1px solid #ddd;border-radius:8px}.ar-row{border-top:1px solid #eee;padding:11px 0}.ar-stars{font-size:18px}.ar-meta{font-size:12px;color:#777;margin:3px 0}.ar-comment{margin-top:5px;line-height:1.5}.ar-empty{padding:20px;text-align:center;color:#777}';document.head.appendChild(s);const b=document.createElement('section');b.id='adminReviewsBox';b.innerHTML='<div class="ar-title">⭐ ĐÁNH GIÁ KHÁCH HÀNG</div><div id="arStats" class="ar-stats"></div><div class="ar-filter"><select id="arRating"><option value="0">Tất cả sao</option><option value="5">5 sao</option><option value="4">4 sao</option><option value="3">3 sao</option><option value="2">2 sao</option><option value="1">1 sao</option></select><select id="arRestaurant"><option value="0">Tất cả cửa hàng</option></select></div><div id="arRows"></div>';const host=document.querySelector('.container');if(host)host.prepend(b);document.getElementById('arRating').onchange=render;document.getElementById('arRestaurant').onchange=render}
  let reviews=[],restaurants=[];
  async function load(){try{restaurants=await api('/rest/v1/restaurants?select=id,name&order=name.asc');reviews=await api('/rest/v1/customer_reviews?select=id,order_id,customer_id,restaurant_id,rating,comment,created_at&order=created_at.desc&limit=500');const sel=document.getElementById('arRestaurant');if(sel)sel.innerHTML='<option value="0">Tất cả cửa hàng</option>'+restaurants.map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('');render()}catch(e){const x=document.getElementById('arRows');if(x)x.innerHTML='<div class="ar-empty">❌ '+esc(e.message)+'</div>'}}
  function render(){const rf=Number(document.getElementById('arRating')?.value||0),rid=Number(document.getElementById('arRestaurant')?.value||0);const all=reviews.filter(x=>(!rf||Number(x.rating)===rf)&&(!rid||Number(x.restaurant_id)===rid));const avg=reviews.length?(reviews.reduce((a,x)=>a+Number(x.rating||0),0)/reviews.length).toFixed(2):'0.00';const dist=n=>reviews.filter(x=>Number(x.rating)===n).length;const st=document.getElementById('arStats');if(st)st.innerHTML=`<div class="ar-stat">Tổng đánh giá<b>${reviews.length}</b></div><div class="ar-stat">Trung bình<b>⭐ ${avg}</b></div><div class="ar-stat">5★ / 1★<b>${dist(5)} / ${dist(1)}</b></div>`;const rows=document.getElementById('arRows');if(!rows)return;if(!all.length){rows.innerHTML='<div class="ar-empty">Chưa có đánh giá phù hợp.</div>';return}rows.innerHTML=all.map(x=>{const r=restaurants.find(z=>Number(z.id)===Number(x.restaurant_id));return `<div class="ar-row"><div class="ar-stars">${'★'.repeat(Number(x.rating))}${'☆'.repeat(5-Number(x.rating))}</div><div class="ar-meta">${esc(r?.name||'Không xác định')} · Đơn #${esc(x.order_id)} · ${new Date(x.created_at).toLocaleString('vi-VN')}</div><div class="ar-comment">${esc(x.comment||'Không có bình luận')}</div></div>`}).join('')}
  function start(){inject();setTimeout(load,1200);setInterval(load,30000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();