'use strict';
(function(){
const SB='https://guwdswqaqnhzqapflvey.supabase.co',KEY='sb_publishable_AfTScx4Qcwmk3dk8pCo9Fg_kZgglof9',APP='66bec449-f15b-4d0e-90fc-3dc470fef20c';
const $=id=>document.getElementById(id),dbg=t=>{const e=$('adminPushDebug');if(e)e.innerHTML=t};
const token=()=>localStorage.getItem('choco_access_token')||'',uid=()=>localStorage.getItem('choco_user_id')||'';
function b64(s){const p='='.repeat((4-s.length%4)%4),r=atob((s+p).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from(r,c=>c.charCodeAt(0))}
async function vapid(){const r=await fetch(SB+'/functions/v1/admin-push-public',{headers:{apikey:KEY,Accept:'application/json'}}),t=await r.text();let j={};try{j=JSON.parse(t)}catch{}if(!r.ok||!j.vapid_public_key)throw Error('Không lấy được VAPID Public Key Admin');return b64(j.vapid_public_key.trim())}
async function nativeEnable(){if(!token()||!uid())throw Error('Phiên Admin chưa đăng nhập');if(!('serviceWorker'in navigator)||!('PushManager'in window))throw Error('Thiết bị không hỗ trợ Web Push');if(!window.isSecureContext)throw Error('Web Push cần HTTPS');if(/iphone|ipad|ipod/i.test(navigator.userAgent)&&!(navigator.standalone===true||matchMedia('(display-mode:standalone)').matches))throw Error('iPhone cần mở Admin từ Màn hình chính (PWA)');const key=await vapid(),reg=await navigator.serviceWorker.register('./admin-push-sw.js?v=admin6',{scope:'./'});await navigator.serviceWorker.ready;let p=Notification.permission;if(p!=='granted')p=await Notification.requestPermission();if(p!=='granted')throw Error('Bạn chưa cho phép thông báo');let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:key});const j=sub.toJSON();if(!j.endpoint||!j.keys?.p256dh||!j.keys?.auth)throw Error('Subscription Admin thiếu dữ liệu');const r=await fetch(SB+'/rest/v1/rpc/upsert_admin_push_subscription',{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+token(),'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({p_user_id:uid(),p_endpoint:j.endpoint,p_p256dh:j.keys.p256dh,p_auth:j.keys.auth})});if(!r.ok)throw Error('Supabase Admin REST '+r.status+': '+await r.text());localStorage.setItem('choco_admin_push_enabled','1')}
async function loadOS(){if(window.OneSignal)return window.OneSignal;await new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.page.js';s.onload=ok;s.onerror=()=>no(Error('Không tải được OneSignal SDK'));document.head.appendChild(s)});for(let i=0;i<50&&!window.OneSignal;i++)await new Promise(r=>setTimeout(r,100));if(!window.OneSignal)throw Error('OneSignal SDK chưa sẵn sàng');return window.OneSignal}
async function osEnable(){const O=await loadOS();const siteBase='/Choco-foods/';if(!O.__chocoAdminInitialized){try{await O.init({appId:APP,allowLocalhostAsSecureOrigin:false,serviceWorkerPath:'Choco-foods/OneSignalSDKWorker.js',serviceWorkerParam:{scope:siteBase}})}catch(e){if(!String(e?.message||e).toLowerCase().includes('already initialized'))throw e}O.__chocoAdminInitialized=true}try{if(O.login)await O.login(uid())}catch(e){}try{if(O.Notifications?.permission!==true)await O.Notifications.requestPermission()}catch(e){}try{if(O.User?.PushSubscription?.optIn)await O.User.PushSubscription.optIn()}catch(e){}localStorage.setItem('choco_admin_onesignal_enabled','1')}
async function enable(){const b=$('adminPush');if(b)b.disabled=true;dbg('⏳ Đang bật Native Admin...');try{await nativeEnable();$('adminPushStatus').innerHTML='✅ <b>WEB PUSH NATIVE ADMIN ĐÃ BẬT</b>';dbg('✅ Native Admin: ACTIVE');if($('adminPushTest'))$('adminPushTest').disabled=false}catch(e){dbg('❌ Native: '+e.message);if(b)b.disabled=false}}
async function enableOS(){const b=$('adminOneSignal');if(b)b.disabled=true;dbg('⏳ Đang bật OneSignal Admin riêng...');try{await osEnable();dbg('✅ OneSignal Admin: ACTIVE');if($('adminPushTest'))$('adminPushTest').disabled=false}catch(e){dbg('❌ OneSignal: '+e.message)}finally{if(b)b.disabled=false}}
async function send(mode){const r=await fetch(SB+'/functions/v1/admin-send-push?mode='+encodeURIComponent(mode),{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+token(),Accept:'application/json'}}),t=await r.text();let j={};try{j=JSON.parse(t)}catch{}if(!r.ok||j.ok===false)throw Error(j.error||t||('HTTP '+r.status));return j}
async function test(){const b=$('adminPushTest');if(b)b.disabled=true;let out=[];try{const j=await send('test');out.push('Native: '+(j.native?.some(x=>x.ok)?'✅':'❌')+' Target '+(j.target_count??0));out.push('OneSignal: '+(j.onesignal?.ok?'✅':'❌'))}catch(e){out.push('Native/OneSignal: ❌ '+e.message)}dbg('🧪 TEST CẢ 2 KÊNH<br>'+out.join('<br>')+'<br><br>Kiểm tra thông báo trên iPhone.');if(b)b.disabled=false}
let busy=false;
async function watchOrders(){if(busy||!token()||!uid())return;busy=true;try{const j=await send('events');if(j.processed>0)dbg('🔔 Đã xử lý '+j.processed+' thông báo Admin: 📦 đơn mới / ✅ giao thành công')}catch(e){console.error('ADMIN PUSH EVENTS',e)}finally{busy=false}}
function init(){const n=$('adminPush'),o=$('adminOneSignal'),t=$('adminPushTest');if(n)n.onclick=enable;if(o)o.onclick=enableOS; if(t)t.onclick=test;dbg('Admin Push riêng • 📦 đơn mới + ✅ giao thành công • Shipper không bị ảnh hưởng');if(localStorage.getItem('choco_admin_push_enabled')==='1'&&$('adminPushStatus'))$('adminPushStatus').innerHTML='✅ <b>WEB PUSH NATIVE ADMIN ĐÃ BẬT</b>';if(t)t.disabled=false;watchOrders();setInterval(watchOrders,5000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
