/* CHOCO SHIP - CUSTOMER PAGE LOGIN MODULE */
(function(){
  "use strict";
  const U="https://guwdswqaqnhzqapflvey.supabase.co";
  const K="sb_publishable_AfTScx4Qcwmk3dk8pCo9Fg_kZgglof9";
  function decode(t){try{const p=String(t||"").split(".");if(p.length!==3)return null;let b=p[1].replace(/-/g,"+").replace(/_/g,"/");b+="=".repeat((4-b.length%4)%4);return JSON.parse(atob(b))}catch(e){return null}}
  function session(){const t=localStorage.getItem("choco_access_token")||"",c=decode(t);return{token:t,id:c?.sub?String(c.sub):""}}
  function show(){if(document.getElementById("csLogin"))return;const s=document.createElement("style");s.textContent="#csLogin{position:fixed;inset:0;background:rgba(0,0,0,.65);z-index:99999;display:flex;align-items:center;justify-content:center;padding:18px}#csLogin .card{width:100%;max-width:420px;background:#fff;border-radius:20px;padding:22px;box-shadow:0 10px 40px rgba(0,0,0,.3)}#csLogin h2{margin:0 0 6px;color:#ff6b00}#csLogin p{color:#666;font-size:14px;line-height:1.5}#csLogin label{display:block;font-weight:700;margin:12px 0 6px}#csLogin input{width:100%;padding:13px;border:1px solid #ddd;border-radius:10px;font-size:16px}#csLogin button{width:100%;padding:14px;border:0;border-radius:10px;background:#ff6b00;color:#fff;font-weight:800;font-size:16px;margin-top:14px}#csLogin .msg{margin-top:12px;padding:11px;border-radius:10px;font-size:14px;line-height:1.4;display:none}.ok{display:block!important;background:#dcfce7;color:#166534}.err{display:block!important;background:#fee2e2;color:#991b1b}#csLogin a{display:block;text-align:center;margin-top:12px;color:#1677ff;font-weight:700;text-decoration:none}";document.head.appendChild(s);const d=document.createElement("div");d.id="csLogin";d.innerHTML='<div class="card"><h2>🍔 CHOCO SHIP</h2><p>Đăng nhập tài khoản <b>Khách hàng</b> để đặt đơn và theo dõi Shipper.</p><form id="csLoginForm"><label>Email</label><input id="csEmail" type="email" autocomplete="username" required placeholder="Email"><label>Mật khẩu</label><input id="csPass" type="password" autocomplete="current-password" required placeholder="Mật khẩu"><button id="csBtn">🔐 ĐĂNG NHẬP</button></form><div id="csMsg" class="msg"></div><a href="index.html">📝 Đăng ký tài khoản</a></div>';document.body.appendChild(d);document.getElementById("csLoginForm").onsubmit=login}
  function message(t,ok){const e=document.getElementById("csMsg");if(e){e.textContent=t;e.className="msg "+(ok?"ok":"err")}}
  async function login(ev){ev.preventDefault();const b=document.getElementById("csBtn");const email=document.getElementById("csEmail").value.trim().toLowerCase();const password=document.getElementById("csPass").value;b.disabled=true;b.textContent="⏳ ĐANG XÁC THỰC...";try{const r=await fetch(U+"/auth/v1/token?grant_type=password",{method:"POST",headers:{"Content-Type":"application/json",apikey:K},body:JSON.stringify({email,password})});const t=await r.text();let d={};try{d=JSON.parse(t)}catch(e){}if(!r.ok)throw Error(d.error_description||d.msg||d.message||"Email hoặc mật khẩu không đúng.");const token=d.access_token,id=decode(token)?.sub||d.user?.id;if(!token||!id)throw Error("Không lấy được phiên đăng nhập.");const p=await fetch(U+"/rest/v1/choco_v2_auth_profiles?user_id=eq."+encodeURIComponent(id)+"&active=eq.true&select=user_id,role,display_name",{headers:{apikey:K,Authorization:"Bearer "+token,Accept:"application/json"}});if(!p.ok)throw Error("Không thể kiểm tra quyền tài khoản. HTTP "+p.status);const rows=await p.json(),profile=rows[0];if(!profile)throw Error("Tài khoản chưa có hồ sơ quyền.");if(profile.role!=="customer")throw Error("Tài khoản này không phải Khách hàng.");localStorage.setItem("choco_access_token",token);localStorage.setItem("choco_user_id",String(id));localStorage.setItem("choco_role","customer");localStorage.setItem("choco_email",email);if(profile.display_name)localStorage.setItem("choco_customer_name",profile.display_name);message("✅ Đăng nhập thành công!",true);setTimeout(()=>location.reload(),250)}catch(e){message("❌ "+(e.message||String(e)),false);b.disabled=false;b.textContent="🔐 ĐĂNG NHẬP"}}
  const x=session();if(!x.token||!x.id)show();
})();