/* CHOCO SHIP — CUSTOMER CORE FIX v21
 * GPS + reverse geocode + guaranteed delivery-address field fill.
 * FIX v21: bind both GPS buttons on dedicated customer pages.
 * FIX v21: persist name/phone/address immediately after GPS reverse-geocode.
 */
'use strict';
(function(){
  const CART_KEY='choco_customer_cart_v1';
  let requestId=0,timer=null,mapBindTimer=null,mapBound=false;
  const btns=()=>['gpsButton','cartGpsButton'].map(id=>document.getElementById(id)).filter(Boolean);
  const setBtns=(text,disabled)=>btns().forEach(b=>{b.disabled=!!disabled;b.textContent=text});
  const msg=t=>['locationText','cartGpsText'].forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=t});
  const valid=(a,b)=>{const lat=Number(a),lng=Number(b);return Number.isFinite(lat)&&Number.isFinite(lng)&&lat>=-90&&lat<=90&&lng>=-180&&lng<=180&&!(lat===0&&lng===0)};
  const state=()=>window.currentGPS&&valid(window.currentGPS.lat,window.currentGPS.lng)?window.currentGPS:{lat:null,lng:null};
  function cartFoodTotal(){try{const raw=JSON.parse(localStorage.getItem(CART_KEY)||'[]');if(Array.isArray(raw))return raw.reduce((sum,x)=>sum+(Number(x?.price)||0)*(Math.max(1,Math.min(99,Number(x?.qty??x?.quantity)||1))),0)}catch(e){console.warn('[CHOCO CART TOTAL]',e)}const c=Array.isArray(window.cart)?window.cart:[];return c.reduce((sum,x)=>sum+(Number(x?.price)||0)*(Math.max(1,Math.min(99,Number(x?.qty??x?.quantity)||1))),0)}
  function display(){const g=state(),persisted=cartFoodTotal(),legacy=typeof getFoodTotal==='function'?Number(getFoodTotal())||0:0,food=persisted>0?persisted:legacy,ship=20000;[['foodTotal',food],['shippingFee',ship],['shippingTotal',ship],['total',food+ship]].forEach(([id,v])=>{const e=document.getElementById(id);if(e)e.textContent=Number(v).toLocaleString('vi-VN')+'đ'});const d=document.getElementById('shippingDistance');if(d)d.textContent=g.lat==null?'Chưa chọn vị trí':'Đang tính theo nhà hàng';const s=document.getElementById('selectedGPS');if(s)s.textContent=g.lat==null?'Chưa chọn':g.lat.toFixed(6)+', '+g.lng.toFixed(6)}
  async function reverseText(lat,lng){const bdc='https://api.bigdatacloud.net/data/reverse-geocode-client?latitude='+encodeURIComponent(lat)+'&longitude='+encodeURIComponent(lng)+'&localityLanguage=vi',nom='https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat='+encodeURIComponent(lat)+'&lon='+encodeURIComponent(lng)+'&zoom=18&addressdetails=1&accept-language=vi';try{const r=await Promise.race([fetch(bdc,{cache:'no-store'}),new Promise((_,rej)=>setTimeout(()=>rej(Error('timeout')),4500))]);if(r.ok){const d=await r.json(),a=[];['road','neighbourhood','locality','city','principalSubdivision'].forEach(k=>{if(d[k]&&!a.includes(d[k]))a.push(d[k])});if(d.localityInfo?.administrative)d.localityInfo.administrative.map(x=>x?.name).filter(Boolean).forEach(x=>{if(!a.includes(x))a.push(x)});if(a.length)return a.slice(0,7).join(', ')}}catch(e){console.warn('[CHOCO ADDRESS BDC]',e)}try{const r=await Promise.race([fetch(nom,{cache:'no-store'}),new Promise((_,rej)=>setTimeout(()=>rej(Error('timeout')),4500))]);if(r.ok){const d=await r.json();if(d.display_name)return d.display_name}}catch(e){console.warn('[CHOCO ADDRESS NOMINATIM]',e)}return ''}
  function putAddress(value,lat,lng,onlyIfGpsFallback){const text=String(value||'').trim();if(!text)return false;const el=document.getElementById('address');if(!el)return false;const gpsFallback='GPS '+lat.toFixed(6)+', '+lng.toFixed(6);if(onlyIfGpsFallback&&el.value.trim()&&el.value.trim()!==gpsFallback)return false;el.value=text;el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));try{el.focus();el.blur()}catch{}try{window.__CHOCO_PERSIST_DELIVERY__?.()}catch{}return true}
  async function address(lat,lng,source){const fallback='GPS '+lat.toFixed(6)+', '+lng.toFixed(6),fromMap=source==='Bản đồ';putAddress(fallback,lat,lng,false);const text=await reverseText(lat,lng);if(text)putAddress(text,lat,lng,!fromMap);const ct=document.getElementById('cartGpsText');if(ct)ct.textContent=(fromMap?'🗺️ ':'📍 ')+(text||'Đã chọn vị trí')+'\nGPS: '+lat.toFixed(6)+', '+lng.toFixed(6);try{window.__CHOCO_PERSIST_DELIVERY__?.()}catch{}}
  function apply(lat,lng,label){lat=Number(lat);lng=Number(lng);if(!valid(lat,lng))return false;const source=label||'GPS';window.currentGPS={lat,lng,source};try{localStorage.setItem('choco_customer_gps_v1',JSON.stringify({lat,lng,source,updated_at:new Date().toISOString()}))}catch{}const lt=document.getElementById('locationText');if(lt)lt.innerHTML=(source==='Bản đồ'?'🗺️':'📍')+' <b>Vị trí giao hàng:</b><br>'+lat.toFixed(6)+', '+lng.toFixed(6);display();msg((source==='Bản đồ'?'🗺️ Đã chọn vị trí trên bản đồ. Đang lấy địa chỉ...':'📍 GPS đã lấy thành công. Đang điền địa chỉ...')+'\nGPS: '+lat.toFixed(6)+', '+lng.toFixed(6));address(lat,lng,source);return true}
  function run(){const id=++requestId;if(timer){clearTimeout(timer);timer=null}if(!window.isSecureContext){msg('⚠️ GPS cần HTTPS.');return}if(!navigator.geolocation){msg('⚠️ Thiết bị không hỗ trợ GPS.');return}setBtns('⏳ ĐANG LẤY GPS...',true);msg('📍 Đang xin vị trí hiện tại...');let retried=false,done=false;const finish=()=>{if(done||id!==requestId)return;done=true;if(timer){clearTimeout(timer);timer=null}setBtns('📍 LẤY / CẬP NHẬT GPS GIAO HÀNG',false)},ok=p=>{if(done||id!==requestId)return;const lat=Number(p?.coords?.latitude),lng=Number(p?.coords?.longitude);if(!valid(lat,lng)){fail({code:2});return}finish();apply(lat,lng,'GPS')},fail=e=>{if(done||id!==requestId)return;if(!retried){retried=true;try{navigator.geolocation.getCurrentPosition(ok,fail,{enableHighAccuracy:false,timeout:8000,maximumAge:60000});return}catch{}}finish();const c=(()=>{try{return JSON.parse(localStorage.getItem('choco_customer_gps_v1')||'null')}catch{return null}})();if(c&&valid(c.lat,c.lng)){apply(c.lat,c.lng,'GPS gần nhất');return}msg(e?.code===1?'⚠️ Safari chưa được cấp quyền vị trí. Hãy bật Dịch vụ định vị + Vị trí chính xác.':e?.code===2?'⚠️ Không xác định được vị trí. Hãy bật Wi‑Fi/4G và thử lại.':'⚠️ GPS phản hồi quá chậm. Bạn có thể chạm trực tiếp lên bản đồ.')};try{navigator.geolocation.getCurrentPosition(ok,fail,{enableHighAccuracy:true,timeout:12000,maximumAge:60000})}catch(e){fail({code:2})}timer=setTimeout(()=>fail({code:3}),13000)}
  function openMapPickerFromCart(){try{const mapEl=document.getElementById('map');if(mapEl){mapEl.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>{try{window.__CHOCO_MAPLIBRE__?.resize?.();window.map?.invalidateSize?.()}catch{}},450)}const t=document.getElementById('locationText');if(t)t.innerHTML='🗺️ <b>Chạm BẤT KỲ điểm nào trên bản đồ để chọn vị trí giao hàng</b>'}catch(e){console.warn('[CHOCO MAP PICKER]',e)}}
  function bind(){const g=document.getElementById('gpsButton'),c=document.getElementById('cartGpsButton');if(g&&!g.__chocoBound){g.__chocoBound=true;g.addEventListener('click',e=>{e.preventDefault();run()},{capture:true})}if(c&&!c.__chocoBound){c.__chocoBound=true;c.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();run()},{capture:true})}}
  function bindCartMapButton(){const b=document.getElementById('cartGpsButton')?.parentElement?.querySelector('.address-map-btn');if(!b||b.__chocoBound)return;b.__chocoBound=true;b.addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();openMapPickerFromCart()},true)}
  window.getGPS=run;window.setDeliveryLocation=(lat,lng)=>apply(lat,lng,'Bản đồ');window.calculateShippingFee=()=>20000;window.updateShippingDisplay=display;
  function bindMap(){try{const m=window.map;if(!m||typeof m.on!=='function')return false;if(mapBound)return true;const handler=e=>{const ll=e?.lngLat;if(ll&&valid(ll.lat,ll.lng)){apply(ll.lat,ll.lng,'Bản đồ');return}const old=e?.latlng;if(old&&valid(old.lat,old.lng))apply(old.lat,old.lng,'Bản đồ')};m.on('click',handler);mapBound=true;return true}catch(e){console.warn('[CHOCO MAP BIND]',e);return false}}
  function watchMap(){if(bindMap())return;if(mapBindTimer)clearInterval(mapBindTimer);let tries=0;mapBindTimer=setInterval(()=>{tries++;if(bindMap()||tries>=40){clearInterval(mapBindTimer);mapBindTimer=null}},250)}
  function init(){setBtns('📍 LẤY / CẬP NHẬT GPS GIAO HÀNG',false);display();bind();watchMap();bindCartMapButton();setTimeout(bind,500);setTimeout(bindCartMapButton,500);setTimeout(bind,1500);setTimeout(bindCartMapButton,1500)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();