'use strict';
(function(){
const SB='https://guwdswqaqnhzqapflvey.supabase.co',KEY='sb_publishable_AfTScx4Qcwmk3dk8pCo9Fg_kZgglof9',AUTH_KEY='sb-guwdswqaqnhzqapflvey-auth-token';
function session(){try{const x=JSON.parse(localStorage.getItem(AUTH_KEY)||'null');if(x?.access_token&&x?.user?.id)return x;if(x?.currentSession?.access_token&&x?.currentSession?.user?.id)return x.currentSession}catch(_){ }return null}
const token=()=>session()?.access_token||localStorage.getItem('choco_access_token')||'';
const uid=()=>session()?.user?.id||localStorage.getItem('choco_user_id')||'';
function b64(s){const p='='.repeat((4-s.length%4)%4),r=atob((s+p).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from(r,c=>c.charCodeAt(0))}
function jwtExpired(t){try{const p=t.split('.')[1];const j=JSON.parse(new TextDecoder().decode(b64(p)));return !j.exp||Date.now()/1000>=j.exp-30}catch(_){return true}}
async function refresh(){const s=session();if(!s?.refresh_token)return null;const r=await fetch(SB+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({refresh_token:s.refresh_token})});if(!r.ok)return null;const d=await r.json();if(!d?.access_token||!d?.user?.id)return null;localStorage.setItem(AUTH_KEY,JSON.stringify({access_token:d.access_token,refresh_token:d.refresh_token||s.refresh_token,user:d.user,token_type:d.token_type||'bearer',expires_in:d.expires_in,expires_at:d.expires_at||Math.floor(Date.now()/1000)+Number(d.expires_in||3600)}));localStorage.setItem('choco_access_token',d.access_token);localStorage.setItem('choco_user_id',d.user.id);return d.access_token}
async function validToken(){let t=token();if(!t)throw Error('Bạn chưa đăng nhập');if(jwtExpired(t)){t=await refresh();if(!t)throw Error('Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.')}return t}
async function enable(){const t=await validToken(),u=uid();if(!u)throw Error('Không xác định được tài khoản khách');if(!('serviceWorker'in navigator)||!('PushManager'in window))throw Error('Thiết bị không hỗ trợ Web Push');if(!window.isSecureContext)throw Error('Web Push cần HTTPS');if(/iphone|ipad|ipod/i.test(navigator.userAgent)&&!(navigator.standalone===true||matchMedia('(display-mode:standalone)').matches))throw Error('iPhone cần mở CHOCO SHIP từ Màn hình chính (PWA)');
 const vr=await fetch(SB+'/functions/v1/send-push?mode=public',{headers:{apikey:KEY,Accept:'application/json'}}),vj=await vr.json();if(!vr.ok||!vj.vapid_public_key)throw Error('Không lấy được VAPID Public Key');
 const reg=await navigator.serviceWorker.register('./customer-push-sw.js?v=20260907-3',{scope:'./',updateViaCache:'none'});await reg.update();await navigator.serviceWorker.ready;let p=Notification.permission;if(p!=='granted')p=await Notification.requestPermission();if(p!=='granted')throw Error(p==='denied'?'Thông báo đang bị chặn trên iPhone. Hãy bật thông báo cho CHOCO SHIP.':'Bạn chưa cho phép thông báo');
 let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64(vj.vapid_public_key.trim())});const j=sub.toJSON();if(!j.endpoint||!j.keys?.p256dh||!j.keys?.auth)throw Error('Subscription Web Push không hợp lệ');
 const r=await fetch(SB+'/functions/v1/register-push',{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+t,'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({user_id:u,role:'customer',subscription:{endpoint:j.endpoint,keys:{p256dh:j.keys.p256dh,auth:j.keys.auth}}})});const text=await r.text();let data={};try{data=JSON.parse(text)}catch{}if((r.status===401||r.status===403)&&session()?.refresh_token){const nt=await refresh();if(nt){return enable()}}if(!r.ok||!data.ok)throw Error(data.error||text||('HTTP '+r.status));localStorage.setItem('choco_customer_push_enabled','1');return data;}
async function testNotification(){if(Notification.permission!=='granted')throw Error('Hãy bật thông báo trước');const reg=await navigator.serviceWorker.ready;const worker=reg.active||reg.waiting||reg.installing;if(!worker)throw Error('Service Worker chưa sẵn sàng');worker.postMessage({type:'CHOCO_TEST_NOTIFICATION'});return true}
function mount(){if(document.getElementById('customerPushBox'))return;const box=document.createElement('div');box.id='customerPushBox';box.style.cssText='background:#eff6ff;border:1px solid #bfdbfe;padding:12px;border-radius:12px;margin:12px 0;font-size:14px;line-height:1.5';box.innerHTML='<b>🔔 Thông báo đơn hàng</b><div id="customerPushText" style="margin:6px 0;color:#555">Bật thông báo để nhận cập nhật đơn ngay cả khi đóng app.</div><div style="display:flex;gap:8px;flex-wrap:wrap"><button id="customerPushBtn" style="border:0;background:#1677ff;color:#fff;padding:10px 13px;border-radius:9px;font-weight:bold">🔔 BẬT THÔNG BÁO</button><button id="customerPushTest" style="border:0;background:#16a34a;color:#fff;padding:10px 13px;border-radius:9px;font-weight:bold">🧪 TEST THÔNG BÁO</button></div>';
 const target=document.querySelector('.container');if(target)target.prepend(box);const btn=box.querySelector('#customerPushBtn'),test=box.querySelector('#customerPushTest'),txt=box.querySelector('#customerPushText');btn.onclick=async()=>{btn.disabled=true;txt.textContent='⏳ Đang bật thông báo...';try{await enable();txt.textContent='✅ Thông báo đơn hàng đã bật.';btn.textContent='✅ ĐÃ BẬT'}catch(e){txt.textContent='❌ '+(e?.message||String(e));btn.disabled=false}};test.onclick=async()=>{test.disabled=true;txt.textContent='🧪 Đang gửi thông báo test...';try{await testNotification();txt.textContent='✅ Đã gửi test. Kiểm tra màn hình khóa / Trung tâm thông báo.'}catch(e){txt.textContent='❌ '+(e?.message||String(e));}finally{test.disabled=false}};
 if(localStorage.getItem('choco_customer_push_enabled')==='1'){txt.textContent='✅ Thông báo đơn hàng đã bật.';btn.textContent='✅ ĐÃ BẬT';btn.disabled=true}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
window.CHOCOSHIPCustomerPush={enable,refresh,testNotification};
})();