'use strict';
(function(){
const SB='https://guwdswqaqnhzqapflvey.supabase.co',KEY='sb_publishable_AfTScx4Qcwmk3dk8pCo9Fg_kZgglof9',REGISTER_URL=SB+'/functions/v1/register-push',PUBLIC_URL=SB+'/functions/v1/send-push?mode=public',AUTH_KEY='sb-guwdswqaqnhzqapflvey-auth-token';
const $=x=>document.getElementById(x),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function session(){try{const x=JSON.parse(localStorage.getItem(AUTH_KEY)||'null');if(x?.access_token&&x?.user?.id)return x;if(x?.currentSession?.access_token&&x?.currentSession?.user?.id)return x}catch(_){ }return null}
const token=()=>session()?.access_token||localStorage.getItem('choco_access_token')||'';
const uid=()=>session()?.user?.id||localStorage.getItem('choco_user_id')||'';
function iosPwa(){return /iphone|ipad|ipod/i.test(navigator.userAgent)&&(navigator.standalone===true||matchMedia('(display-mode:standalone)').matches)}
function b64(s){const p='='.repeat((4-s.length%4)%4);const r=atob((s+p).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from(r,c=>c.charCodeAt(0))}
function endpointId(endpoint){let h=0;for(let i=0;i<endpoint.length;i++)h=((h<<5)-h+endpoint.charCodeAt(i))|0;return 'wp_'+Math.abs(h).toString(36)+'_'+endpoint.length}
function jwtExpired(t){try{const p=t.split('.')[1],j=JSON.parse(new TextDecoder().decode(b64(p)));return !j.exp||Date.now()/1000>=j.exp-30}catch(_){return true}}
async function refresh(){const s=session();if(!s?.refresh_token)return null;const r=await fetch(SB+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({refresh_token:s.refresh_token})});if(!r.ok)return null;const d=await r.json();if(!d?.access_token||!d?.user?.id)return null;localStorage.setItem(AUTH_KEY,JSON.stringify({access_token:d.access_token,refresh_token:d.refresh_token||s.refresh_token,user:d.user,token_type:d.token_type||'bearer',expires_in:d.expires_in,expires_at:d.expires_at||Math.floor(Date.now()/1000)+Number(d.expires_in||3600)}));localStorage.setItem('choco_access_token',d.access_token);localStorage.setItem('choco_user_id',d.user.id);return d.access_token}
async function validToken(){let t=token();if(!t)throw Error('Bạn chưa đăng nhập');if(jwtExpired(t)){t=await refresh();if(!t)throw Error('Phiên đăng nhập khách đã hết hạn. Vui lòng đăng nhập lại.')}return t}
async function getVapidPublic(){const r=await fetch(PUBLIC_URL,{headers:{apikey:KEY,Accept:'application/json'}});const t=await r.text();let b={};try{b=JSON.parse(t)}catch{}if(!r.ok||!b.vapid_public_key)throw Error('Không lấy được VAPID Public Key từ máy chủ');return b.vapid_public_key.trim()}
async function getNativeRegistration(){const regs=await navigator.serviceWorker.getRegistrations();return regs.find(r=>String(r.active?.scriptURL||r.installing?.scriptURL||r.waiting?.scriptURL||'').includes('/customer-push-sw.js'))||null}
async function registerNativePush(){const button=$('customerPushBtn'),status=$('customerPushText'),debug=$('customerPushDebug');try{if(!('serviceWorker'in navigator))throw Error('Thiết bị không hỗ trợ Service Worker');if(!('PushManager'in window))throw Error('Thiết bị không hỗ trợ Web Push');if(!('Notification'in window))throw Error('Thiết bị không hỗ trợ thông báo');if(location.protocol!=='https:')throw Error('Web Push cần HTTPS');if(/iphone|ipad|ipod/i.test(navigator.userAgent)&&!iosPwa())throw Error('iPhone cần mở CHOCO SHIP từ Màn hình chính (PWA)');const t=await validToken(),u=uid();if(!u)throw Error('Không xác định được tài khoản khách');button.disabled=true;status.textContent='⏳ Đang bật thông báo...';debug.textContent='⏳ Đang kiểm tra quyền thông báo...';let permission=Notification.permission;if(permission!=='granted')permission=await Notification.requestPermission();if(permission!=='granted')throw Error(permission==='denied'?'Thông báo đang bị chặn. Hãy cho phép CHOCO SHIP trong cài đặt iPhone.':'Bạn chưa cho phép thông báo');debug.textContent='⏳ Đang cài Service Worker Native (giống Shipper)...';let reg=await getNativeRegistration();if(!reg)reg=await navigator.serviceWorker.register('./customer-push-sw.js?v=20260907-5',{scope:'./native-push/',updateViaCache:'none'});await reg.update();await reg.ready;const vapid=await getVapidPublic(),appKey=b64(vapid);if(appKey.length!==65||appKey[0]!==4)throw Error('VAPID Public Key không hợp lệ');debug.textContent='⏳ Đang kiểm tra Web Push subscription...';let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:appKey});if(!sub?.endpoint)throw Error('Không tạo được Web Push subscription');const j=sub.toJSON();if(!j.keys?.p256dh||!j.keys?.auth)throw Error('Subscription Web Push thiếu p256dh hoặc auth');const sid=endpointId(sub.endpoint);debug.innerHTML='⏳ Đang lưu subscription...<br>Subscription: '+esc(sid);const r=await fetch(REGISTER_URL,{method:'POST',headers:{'Content-Type':'application/json',apikey:KEY,Authorization:'Bearer '+t,Accept:'application/json'},body:JSON.stringify({shipper_id:null,subscription_id:sid,subscription:{endpoint:sub.endpoint,keys:j.keys}})});const text=await r.text();let body={};try{body=JSON.parse(text)}catch{}if((r.status===401||r.status===403)&&session()?.refresh_token){const nt=await refresh();if(nt)return registerNativePush()}if(!r.ok||body.ok===false)throw Error(body.error||body.message||text||('HTTP '+r.status));localStorage.setItem('choco_customer_push_enabled','1');status.innerHTML='✅ <b>ĐÃ BẬT THÔNG BÁO</b>';debug.innerHTML='Web Push: ACTIVE<br>Permission: YES<br>Service Worker: Native scope riêng<br>Subscription: '+esc(sid);button.textContent='✅ THÔNG BÁO ĐÃ BẬT';}catch(e){button.disabled=false;status.textContent='❌ '+(e?.message||String(e));debug.textContent='❌ '+(e?.message||String(e))}}
async function localNotificationTest(){const button=$('customerPushTest');try{button.disabled=true;if(!('serviceWorker'in navigator))throw Error('Thiết bị không hỗ trợ Service Worker');if(!('Notification'in window))throw Error('Thiết bị không hỗ trợ thông báo');if(Notification.permission!=='granted')throw Error('Chưa cấp quyền thông báo. Hãy bấm BẬT THÔNG BÁO trước.');const reg=await getNativeRegistration();if(!reg?.active)throw Error('Native Service Worker chưa active');reg.active.postMessage({type:'CHOCO_TEST_NOTIFICATION'});$('customerPushText').textContent='🧪 Đã gửi lệnh TEST cho Service Worker Native';$('customerPushDebug').textContent='🧪 Test Push nội bộ đã được gửi.';setTimeout(()=>button.disabled=false,1500)}catch(e){button.disabled=false;$('customerPushDebug').textContent='❌ '+(e?.message||String(e))}}
function mount(){if(document.getElementById('customerPushBox'))return;const box=document.createElement('div');box.id='customerPushBox';box.style.cssText='background:#eff6ff;border:1px solid #bfdbfe;padding:14px;border-radius:14px;margin:12px 0;font-size:14px;line-height:1.5';box.innerHTML='<b>🔔 Thông báo đơn hàng</b><div id="customerPushText" style="margin:7px 0;color:#555">Bật thông báo để nhận cập nhật đơn ngay cả khi đóng app.</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><button id="customerPushBtn" style="border:0;background:#1677ff;color:#fff;padding:11px 10px;border-radius:10px;font-weight:bold">🔔 BẬT THÔNG BÁO</button><button id="customerPushTest" style="border:0;background:#16a34a;color:#fff;padding:11px 10px;border-radius:10px;font-weight:bold">🧪 TEST THÔNG BÁO</button></div><div id="customerPushDebug" style="margin-top:9px;background:#f3f4f6;padding:9px;border-radius:9px;font-size:12px;word-break:break-word">Web Push native • cơ chế giống Shipper</div>';const target=document.querySelector('.container')||document.body;target.prepend(box);box.querySelector('#customerPushBtn').onclick=registerNativePush;box.querySelector('#customerPushTest').onclick=localNotificationTest;if(localStorage.getItem('choco_customer_push_enabled')==='1'){$('customerPushText').innerHTML='✅ <b>ĐÃ BẬT THÔNG BÁO</b>';$('customerPushBtn').textContent='✅ THÔNG BÁO ĐÃ BẬT'}}
function loadOneSignalCustomer(){if(document.getElementById('onesignalCustomerScript'))return;const s=document.createElement('script');s.id='onesignalCustomerScript';s.src='./onesignal-customer.js?v=20260907-1';s.defer=true;document.head.appendChild(s)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{mount();loadOneSignalCustomer()});else{mount();loadOneSignalCustomer()}
window.CHOCOSHIPCustomerPush={enable:registerNativePush,test:localNotificationTest,refresh};
})();
