/* CHOCO SHIP - CUSTOMER REVIEW v1 */
'use strict';
(function(){
  if(window.__CHOCO_CUSTOMER_REVIEW__)return;
  window.__CHOCO_CUSTOMER_REVIEW__=true;
  const SB='https://guwdswqaqnhzqapflvey.supabase.co';
  const KEY='sb_publishable_AfTScx4Qcwmk3dk8pCo9Fg_kZgglof9';
  const AUTH_KEY='sb-guwdswqaqnhzqapflvey-auth-token';
  const esc=x=>String(x??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  function jwt(t){try{const p=String(t||'').split('.')[1];if(!p)return null;return JSON.parse(atob(p.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-p.length%4)%4)))}catch{return null}}
  function session(){try{let s=JSON.parse(localStorage.getItem(AUTH_KEY)||'null');if(s?.session)s=s.session;if(s?.access_token)return s}catch{}return null}
  function order(){try{return JSON.parse(localStorage.getItem('choco_ship_last_order')||'null')}catch{return null}}
  function auth(){const s=session();if(s?.access_token)return{token:s.access_token,id:String(s.user?.id||jwt(s.access_token)?.sub||'')};const t=localStorage.getItem('choco_access_token')||'';return{token:t,id:String(jwt(t)?.sub||localStorage.getItem('choco_user_id')||'')}}
  function inject(){if(document.getElementById('customerReviewBox'))return;const style=document.createElement('style');style.textContent='#customerReviewBox{background:#fff;border-radius:15px;padding:15px;margin:12px 0;box-shadow:0 2px 8px #ddd;border:1px solid #eee}.cr-title{font-size:19px;font-weight:900}.cr-stars{display:flex;gap:6px;margin:12px 0}.cr-star{border:0;background:#eee;border-radius:9px;width:48px;height:44px;font-size:27px}.cr-star.active{background:#fff1d6}.cr-comment{width:100%;min-height:80px;padding:11px;border:1px solid #ddd;border-radius:10px;resize:vertical;font-size:15px;box-sizing:border-box}.cr-save{width:100%;border:0;border-radius:10px;padding:12px;margin-top:10px;background:#ff6b00;color:#fff;font-weight:900;font-size:16px}.cr-msg{margin-top:9px;font-size:13px}';document.head.appendChild(style);const b=document.createElement('section');b.id='customerReviewBox';b.style.display='none';b.innerHTML='<div class="cr-title">⭐ ĐÁNH GIÁ ĐƠN HÀNG</div><div id="crOrder" style="margin-top:6px;color:#555"></div><div id="crStars" class="cr-stars"></div><textarea id="crComment" class="cr-comment" maxlength="1000" placeholder="Chia sẻ trải nghiệm của bạn (không bắt buộc)"></textarea><button id="crSave" class="cr-save">⭐ GỬI ĐÁNH GIÁ</button><div id="crMsg" class="cr-msg"></div>';const host=document.querySelector('.container');if(host)host.appendChild(b);for(let i=1;i<=5;i++){const x=document.createElement('button');x.type='button';x.className='cr-star';x.textContent='☆';x.dataset.rating=i;x.onclick=()=>{document.querySelectorAll('.cr-star').forEach((s,j)=>{s.textContent=j<i?'★':'☆';s.classList.toggle('active',j<i)});b.dataset.rating=i};document.getElementById('crStars').appendChild(x)}document.getElementById('crSave').onclick=save}
  async function api(path,opt={}){const a=auth();if(!a.token)throw Error('Vui lòng đăng nhập tài khoản khách.');const r=await fetch(SB+path,{...opt,headers:{apikey:KEY,Authorization:'Bearer '+a.token,Accept:'application/json','Content-Type':'application/json',...(opt.headers||{})}});if(!r.ok)throw Error(await r.text());return r.status===204?null:r.json()}
  async function refresh(){const b=document.getElementById('customerReviewBox'),o=order();if(!b||!o?.code)return;const a=auth();if(!a.token||!a.id)return;try{const rows=await api('/rest/v1/orders?select=id,code,status,customer_id&code=eq.'+encodeURIComponent(o.code)+'&customer_id=eq.'+encodeURIComponent(a.id)+'&status=eq.Hoàn%20thành&limit=1');const ord=rows?.[0];if(!ord){b.style.display='none';return}b.style.display='block';document.getElementById('crOrder').innerHTML='Đơn <b>'+esc(ord.code)+'</b> đã hoàn thành. Bạn đánh giá thế nào?';const existing=await api('/rest/v1/customer_reviews?select=id,rating,comment&order_id=eq.'+encodeURIComponent(ord.id)+'&customer_id=eq.'+encodeURIComponent(a.id)+'&limit=1');if(existing?.[0]){b.dataset.reviewId=existing[0].id;b.dataset.rating=existing[0].rating;document.getElementById('crComment').value=existing[0].comment||'';document.querySelectorAll('.cr-star').forEach((s,j)=>{s.textContent=j<existing[0].rating?'★':'☆';s.classList.toggle('active',j<existing[0].rating)});document.getElementById('crSave').textContent='✏️ CẬP NHẬT ĐÁNH GIÁ';document.getElementById('crMsg').textContent='✅ Bạn đã đánh giá đơn này. Có thể chỉnh sửa.'}else{b.dataset.reviewId='';document.getElementById('crSave').textContent='⭐ GỬI ĐÁNH GIÁ';document.getElementById('crMsg').textContent=''}}catch(e){console.warn('CUSTOMER REVIEW:',e)}}
  async function save(){const b=document.getElementById('customerReviewBox'),msg=document.getElementById('crMsg'),btn=document.getElementById('crSave'),o=order(),a=auth();const rating=Number(b?.dataset.rating||0);if(!rating){msg.textContent='❌ Vui lòng chọn từ 1 đến 5 sao.';return}if(!o?.code||!a.id)return;btn.disabled=true;msg.textContent='⏳ Đang lưu...';try{const rows=await api('/rest/v1/orders?select=id,customer_id,status&code=eq.'+encodeURIComponent(o.code)+'&customer_id=eq.'+encodeURIComponent(a.id)+'&status=eq.Hoàn%20thành&limit=1');const ord=rows?.[0];if(!ord)throw Error('Không tìm thấy đơn đã hoàn thành.');let restaurantId=null;try{const items=Array.isArray(o.items)?o.items:[];restaurantId=Number(items[0]?.restaurantId||items[0]?.restaurant_id||0)||null}catch{}const body={order_id:ord.id,customer_id:a.id,restaurant_id:restaurantId,rating,comment:String(document.getElementById('crComment').value||'').trim()};await api('/rest/v1/customer_reviews?on_conflict=order_id,customer_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(body)});msg.textContent='✅ Đã lưu đánh giá. Cảm ơn bạn!';btn.textContent='✏️ CẬP NHẬT ĐÁNH GIÁ';}catch(e){msg.textContent='❌ '+esc(e.message)}finally{btn.disabled=false}}
  function start(){inject();setTimeout(refresh,1200);setInterval(refresh,10000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();