/* CHOCO SHIP - CUSTOMER FIX v4 */
(function(){
'use strict';
const U='https://guwdswqaqnhzqapflvey.supabase.co';
const K='sb_publishable_AfTScx4Qcwmk3dk8pCo9Fg_kZgglof9';
const PHU_QUOC={lat:10.2899,lng:103.984};
function jwt(t){try{const p=String(t||'').split('.')[1];if(!p)return null;return JSON.parse(atob(p.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-p.length%4)%4)));}catch(e){return null;}}
function auth(){const token=localStorage.getItem('choco_access_token')||'',p=jwt(token);return{token,id:String(p&&p.sub||localStorage.getItem('choco_user_id')||''),email:localStorage.getItem('choco_email')||''};}
function loginUI(){if(document.getElementById('chocoCustomerLogin'))return;const s=document.createElement('style');s.textContent='#chocoCustomerLogin{position:fixed;inset:0;background:#f5f5f5;z-index:99999;display:flex;align-items:center;justify-content:center;padding:18px}.cl-card{width:100%;max-width:420px;background:#fff;border-radius:20px;padding:24px;box-shadow:0 5px 25px #ddd}.cl-logo{text-align:center;color:#ff6b00;font-size:28px;font-weight:900}.cl-sub{text-align:center;color:#777;margin:7px 0 20px}.cl-card label{display:block;font-weight:bold;margin:10px 0 5px}.cl-card input{width:100%;padding:14px;border:1px solid #ddd;border-radius:10px;font-size:16px}.cl-card button{width:100%;padding:14px;border:0;border-radius:10px;background:#ff6b00;color:#fff;font-size:16px;font-weight:bold;margin-top:16px}.cl-msg{margin-top:12px;padding:11px;border-radius:10px;white-space:pre-line}.cl-err{background:#fee2e2;color:#991b1b}.cl-ok{background:#dcfce7;color:#166534}';document.head.appendChild(s);const d=document.createElement('div');d.id='chocoCustomerLogin';d.innerHTML='<div class="cl-card"><div class="cl-logo">🍔 CHOCO SHIP</div><div class="cl-sub">🔐 Đăng nhập tài khoản khách</div><form id="clForm"><label>Email</label><input id="clEmail" type="email" autocomplete="username" required><label>Mật khẩu</label><input id="clPass" type="password" autocomplete="current-password" required><button id="clBtn">🔐 ĐĂNG NHẬP</button></form><div id="clMsg"></div></div>';document.body.appendChild(d);document.getElementById('clForm').onsubmit=async e=>{e.preventDefault();const b=document.getElementById('clBtn'),m=document.getElementById('clMsg');b.disabled=true;b.textContent='⏳ ĐANG ĐĂNG NHẬP...';try{const email=document.getElementById('clEmail').value.trim().toLowerCase(),password=document.getElementById('clPass').value,r=await fetch(U+'/auth/v1/token?grant_type=password',{method:'POST',headers:{'Content-Type':'application/json',apikey:K},body:JSON.stringify({email,password})}),j=await r.json();if(!r.ok)throw Error(j.error_description||j.msg||j.message||'Email hoặc mật khẩu không đúng.');const id=String(j.user&&j.user.id||jwt(j.access_token)?.sub||'');if(!j.access_token||!id)throw Error('Không lấy được phiên đăng nhập.');localStorage.setItem('choco_access_token',j.access_token);localStorage.setItem('choco_user_id',id);localStorage.setItem('choco_role','customer');localStorage.setItem('choco_email',j.user?.email||email);d.remove();location.reload();}catch(err){m.className='cl-msg cl-err';m.textContent='❌ '+err.message;b.disabled=false;b.textContent='🔐 ĐĂNG NHẬP';}};}
function gpsState(){return window.chocoDeliveryGPS||{lat:null,lng:null};}
function setGPS(lat,lng,source){lat=Number(lat);lng=Number(lng);if(!Number.isFinite(lat)||!Number.isFinite(lng))return;window.chocoDeliveryGPS={lat,lng,source:source||'GPS'};window.currentGPS=window.chocoDeliveryGPS;if(window.marker){try{map.removeLayer(window.marker);}catch(e){}}window.marker=L.marker([lat,lng]).addTo(map).bindPopup('📍 Vị trí giao hàng').openPopup();map.setView([lat,lng],16);const txt=lat.toFixed(6)+', '+lng.toFixed(6);const lt=document.getElementById('locationText');if(lt)lt.innerHTML='📍 <b>Vị trí giao hàng:</b><br>'+txt;const sg=document.getElementById('selectedGPS');if(sg)sg.textContent=txt;const ct=document.getElementById('cartGpsText');if(ct)ct.textContent='📍 GPS giao hàng: '+txt;updateDisplay();reverse(lat,lng);}
async function reverse(lat,lng){try{const r=await fetch('https://api.bigdatacloud.net/data/reverse-geocode-client?latitude='+encodeURIComponent(lat)+'&longitude='+encodeURIComponent(lng)+'&localityLanguage=vi');if(!r.ok)return;const d=await r.json(),a=[];['locality','city','principalSubdivision','countryName'].forEach(k=>{if(d[k]&&!a.includes(d[k]))a.push(d[k]);});const address=a.join(', ');const el=document.getElementById('address');if(address&&el&&(!el.value||el.value.indexOf('GPS:')===0)){el.value=address;el.dispatchEvent(new Event('input',{bubbles:true}));}const ct=document.getElementById('cartGpsText');if(ct)ct.textContent='📍 '+(address||'Đã lấy GPS')+'\nGPS: '+lat.toFixed(6)+', '+lng.toFixed(6);}catch(e){console.warn('Reverse geocode:',e);}}
function dist(a,b,c,d){const R=6371,x=(c-a)*Math.PI/180,y=(d-b)*Math.PI/180,z=Math.sin(x/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(y/2)**2;return R*2*Math.atan2(Math.sqrt(z),Math.sqrt(1-z));}
function fee(){const g=gpsState();if(g.lat==null)return 20000;const km=dist(PHU_QUOC.lat,PHU_QUOC.lng,g.lat,g.lng);if(km<=3)return 20000;if(km<=5)return 25000;if(km<=7)return 30000;if(km<=10)return 40000;if(km<=15)return 50000;return 60000;}
function updateDisplay(){if(typeof getFoodTotal!=='function')return;const g=gpsState(),food=getFoodTotal(),ship=fee(),km=g.lat==null?null:dist(PHU_QUOC.lat,PHU_QUOC.lng,g.lat,g.lng);['shippingFee','shippingTotal'].forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=money(ship);});const f=document.getElementById('foodTotal');if(f)f.textContent=money(food);const t=document.getElementById('total');if(t)t.textContent=money(food+ship);const sd=document.getElementById('shippingDistance');if(sd)sd.textContent=km==null?'Chưa chọn vị trí':km.toFixed(1)+' km';const sg=document.getElementById('selectedGPS');if(sg)sg.textContent=g.lat==null?'Chưa chọn':g.lat.toFixed(6)+', '+g.lng.toFixed(6);}
function getGPS(){if(!navigator.geolocation)return alert('❌ Thiết bị không hỗ trợ GPS.');const bs=[document.getElementById('gpsButton'),document.getElementById('cartGpsButton')].filter(Boolean);bs.forEach(b=>{b.disabled=true;b.textContent='⏳ ĐANG LẤY GPS GIAO HÀNG...'});navigator.geolocation.getCurrentPosition(p=>{setGPS(p.coords.latitude,p.coords.longitude,'GPS giao hàng');bs.forEach(b=>{b.disabled=false;b.textContent='📍 CẬP NHẬT GPS GIAO HÀNG'});},e=>{bs.forEach(b=>{b.disabled=false;b.textContent='📍 LẤY GPS GIAO HÀNG'});alert('⚠️ Không lấy được GPS. Hãy bật Quyền vị trí cho Safari và thử lại.\n\nMã lỗi: '+e.code+'\n'+e.message);},{enableHighAccuracy:true,timeout:20000,maximumAge:0});}
async function createOrder(){if(!cart.length)return alert('⚠️ Bạn chưa chọn món.');const name=document.getElementById('name').value.trim(),phone=document.getElementById('phone').value.trim(),address=document.getElementById('address').value.trim(),note=document.getElementById('note').value.trim(),payment=document.getElementById('payment').value,g=gpsState(),a=auth();if(!name)return alert('⚠️ Vui lòng nhập họ tên.');if(!phone)return alert('⚠️ Vui lòng nhập số điện thoại.');if(!address)return alert('⚠️ Vui lòng nhập địa chỉ giao hàng.');if(g.lat==null)return alert('📍 Vui lòng chọn GPS giao hàng.');if(!a.token||!a.id){loginUI();return alert('🔐 Vui lòng đăng nhập tài khoản khách trước khi đặt đơn.');}const foodTotal=getFoodTotal(),shippingFee=fee(),distance=dist(PHU_QUOC.lat,PHU_QUOC.lng,g.lat,g.lng),total=foodTotal+shippingFee,code='CS'+Date.now().toString().slice(-6),order={code,name,phone,address,note,payment,items:JSON.stringify(cart),food_total:foodTotal,shipping_fee:shippingFee,total,status:'Chờ xác nhận',time:new Date().toISOString(),latitude:g.lat,longitude:g.lng,distance_km:Number(distance.toFixed(2)),customer_id:a.id};const btn=document.getElementById('orderButton');btn.disabled=true;btn.textContent='⏳ ĐANG GỬI ĐƠN...';try{const r=await fetch(U+'/rest/v1/orders',{method:'POST',headers:{'Content-Type':'application/json',apikey:K,Authorization:'Bearer '+a.token,Prefer:'return=minimal'},body:JSON.stringify(order)});if(!r.ok)throw Error(await r.text());localStorage.setItem('choco_ship_last_order',JSON.stringify(order));try{await fetch(U+'/functions/v1/send-push',{method:'POST',headers:{'Content-Type':'application/json',apikey:K,Authorization:'Bearer '+a.token},body:JSON.stringify({order_id:code,code,title:'🚚 CHOCO SHIP - ĐƠN MỚI',message:'📦 '+name+' vừa đặt đơn '+code+' • '+money(total)})});}catch(e){}const box=document.getElementById('successBox');box.style.display='block';box.innerHTML='🎉 <b>ĐẶT ĐƠN THÀNH CÔNG</b><br><br>📦 Mã đơn: <b>'+code+'</b><br>🍔 Tiền món: <b>'+money(foodTotal)+'</b><br>📏 Khoảng cách: <b>'+distance.toFixed(1)+' km</b><br>🛵 Phí ship: <b>'+money(shippingFee)+'</b><br>💰 Tổng tiền: <b>'+money(total)+'</b><br>📍 GPS giao hàng: <b>'+g.lat.toFixed(6)+', '+g.lng.toFixed(6)+'</b><br>🆔 Customer ID: <b>'+a.id+'</b>';alert('🎉 ĐẶT ĐƠN THÀNH CÔNG!\nMã đơn: '+code);cart=[];updateCart();renderCart();}catch(e){alert('❌ KHÔNG GỬI ĐƯỢC ĐƠN.\n\n'+e.message);}finally{btn.disabled=false;btn.textContent='🚀 ĐẶT ĐƠN';}}
function install(){const a=auth();if(!a.token||!a.id)loginUI();window.getGPS=getGPS;window.setDeliveryLocation=setGPS;window.calculateShippingFee=fee;window.updateShippingDisplay=updateDisplay;window.createOrder=createOrder;const oldClick=window.map?.on;setTimeout(()=>{try{map.off('click');map.on('click',e=>setGPS(e.latlng.lat,e.latlng.lng,'Bản đồ'));}catch(e){}updateDisplay();},100);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();